<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>KampusRadar</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Kriterij I1 (2 b): Entity Framework Core + proizvoljna baza (SQLite) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />

    <!-- Design: potreban za migracije (dotnet ef migrations add ...) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <!-- Tools: naredbe Add-Migration / Update-Database u Package Manager Consoleu (VS 2026) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
