// <auto-generated />
using System;
using KampusRadar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KampusRadar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008090000_InicijalnaMigracija")]
    partial class InicijalnaMigracija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("KampusRadar.Models.Dogadaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojMjesta")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cijena")
                        .HasColumnType("REAL");

                    b.Property<int>("Kategorija")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Pocetak")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PotrebnaPrijava")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Dogadaji");
                });
#pragma warning restore 612, 618
        }
    }
}
